"""Second migration

Revision ID: 631e82cdc040
Revises: 546742d93e22
Create Date: 2023-08-17 23:40:37.301037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631e82cdc040'
down_revision = '546742d93e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
