"""third migration

Revision ID: 75e0d94fb7b3
Revises: c62b89817739
Create Date: 2023-08-21 14:27:36.993959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e0d94fb7b3'
down_revision = 'c62b89817739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
