"""Second migration

Revision ID: c62b89817739
Revises: 84a8cb307f47
Create Date: 2023-08-20 21:41:24.961919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62b89817739'
down_revision = '84a8cb307f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
